import { NextUIProvider, createTheme } from "@nextui-org/react";
import type { AppProps } from "next/app";
import * as React from "react";
import Head from "next/head";

const dark_theme = createTheme({
  type: "dark",
  theme: {}
});

export const App: React.FC<AppProps> = ({ Component, pageProps }) => {
  return (
    <NextUIProvider theme={dark_theme}>
      <Head>
        <title>DSync</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {typeof window === "undefined" ? null : <Component {...pageProps} />}
    </NextUIProvider>
  );
};

export default App;
