import { NextUIProvider, createTheme } from "@nextui-org/react";
import type { AppProps } from "next/app";
import dynamic from "next/dynamic";
import * as React from "react";
import Head from "next/head";

const APIProvider = dynamic(
  () => {
    return import("../src/provider");
  },
  { ssr: false }
);

const dark_theme = createTheme({
  type: "dark",
  theme: {}
});

export const App: React.FC<AppProps> = ({ Component, pageProps }) => {
  return (
    <NextUIProvider theme={dark_theme}>
      <APIProvider>
        <Head>
          <title>DSync</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Component {...pageProps} />
      </APIProvider>
    </NextUIProvider>
  );
};

export default App;
