import * as React from "react";
import type { NextPage } from "next";
import Head from "next/head";

import { StateContext } from "../src/context";

import Card from "@nextui-org/react/card";
import Button from "@nextui-org/react/button";

const Room: React.FC<{ room_id: string }> = (props) => {
  const [state, api] = React.useContext(StateContext);

  const room = state.rooms.find((room) => room.id === state.active_room);

  React.useEffect(() => {
    const interval = setInterval(() => {
      api.sync(props.room_id);
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  }, [props.room_id]);

  if (!room) {
    return <div>Loading room from host...</div>;
  }

  return <Card color="primary">{props.room_id}</Card>;
};

const Home: NextPage = () => {
  const [context, api] = React.useContext(StateContext);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {context.rooms.map((room) => {
          return (
            <Card key={room.id} hoverable onClick={() => api.activateRoom(room.id)}>
              {room.id}
            </Card>
          );
        })}
      </div>

      {context.active_room ? <Room room_id={context.active_room} /> : null}

      <Button auto flat onClick={() => api.createRoom()}>
        Create Room
      </Button>
    </div>
  );
};

export default Home;
