name: Build and Test

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        target: [mac]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: PNPM Install
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build
