name: Release

on:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        target: [mac]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: PNPM Install
        run: pnpm i --frozen-lockfile

      - name: Configure Signaling Server
        run: |
          echo '{"API_ENDPOINT": "188.166.151.111:9987"}' > electron-container/env.json

      - name: Build
        run: pnpm build

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd electron-container && pnpm release -- --${{ matrix.target }}
