name: Release

on:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        target: [mac]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: PNPM Install
        run: pnpm i --frozen-lockfile

      - name: Configure Signaling Server
        run: |
          echo '{"API_ENDPOINT": "188.166.151.111:9987"}' > electron-container/env.json

      - name: Build
        run: pnpm build

      - name: Import Code-Signing Certificates
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_SIGNING_CERT_P12 }}
          p12-password: ${{ secrets.APPLE_SIGNING_CERT_PASSPHRASE }}

      - name: Trust Cert
        run: |
          echo -n ${{ secrets.APPLE_SIGNING_CERT_CER }} | base64 -D > cert.cer
          security add-trusted-cert -d -r trustRoot -p codeSign -k signing_temp.keychain cert.cer
          rm cert.cer

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_KEYCHAIN: signing_temp.keychain
          CSC_KEY_PASSWORD: ${{ secrets.APPLE_SIGNING_CERT_PASSPHRASE }}
        run: cd electron-container && pnpm release -- --${{ matrix.target }}
